prompt = """
There is a cult of sorcerers in the land of Moulden. These sorcerers are primarily
gnomish and halfing street children that have been coaxed into joining this cult
by the young green dragon, Norvaax. The following is a list of possible names for such
a group that is named after their dragon leader:

- Norvaax's Children 
"""

[model_config]
variant = "Quantized"
device = "Metal"
flash_attn = false

[model_config.model_source.HuggingFaceHub]
revision = "main"

[run_config]
seed = 299792458
sample_len = 150
repeat_penalty = 1.3
repeat_last_n = 64
temperature = 1e-7
