[normal]
0 = "beginning"
"$" = "end"
q = "quit"
esc = "escape"
i = "edit"
a = "edit"
k = "up"
up = "up"
j = "down"
down = "down"
h = "left"
left = "left"
r = "refresh"
w = "right_word"
b = "left_word"
enter = "enter"
backspace = "left"
space = "popup"

[edit]
esc = "escape"
up = "up"
down = "down"
left = "left"
enter = "enter"
backspace = "backspace"
